### ISSUE TITLE
Mettre à jour la page d'accueil du site web

### ISSUE THREAD

**Issue by proxima-admin** [proxima-cm/proxima-cm.github.io#1]
Le site web proxima.cm est en ligne et déployé sur GitHub Pages

L'objectif de ce ticket est de mettre à jour le contenu du site web:

1. la présentation, le titre et la descption meta pour le référencement SEO doit être mise à jour
2. tous les liens qui sont sur la page du site web doivent redirigé vers des pages existantes 
3. Ajouter les pages pour nos produits AlphaDSF, ProximaSMS, Baker et Schooler

**Comment by franklinlemaire** [comment]
Bonjour @proxima-admin , un souci svp le tableau de bord ne s'affiche dans l'onglet projet que faire?

**Comment by Ab0698** [comment]
Bonjour @proxima-admin , @abdounasser202 , @franklinlemaire , après analyse du site web actuelle , je propose qu'on modifie elements suivants : 
1-le Header , on change la barre de navigation , actuellement nous avons les onglets aphadsf , decouvrirproxima , youtube , blog et contact
je propose qu'on modifie cela en remplaçant par acceuil , presentation , produits , contact 
2-Toujours au niveau du Header , je propose qu'on change les images defilantes du site web . on crée d'autres images ou a defaut monter une vidéo qui est très bien faites qui donne un aspect technologiques innovant et professionnel au site web 
3- la parti Qui sommes-nous ? dans le body doit être travailler dans la parti presentation
4-Dans la parti footer , les liens privacy policy , et termes d'utilisation ne renvoie a aucune page , il faut soit les modifier soit les supprimer , en outre il faut modifier l'orthographe des mots pour plus de professionnalisme , comme par exemple remplacer Entrer en contact par Contact tout court , liens rapides part liens utiles , Nos produits par Produits .
Ensuite toujours dans le footer remplacer dans le bas de page la mention TemplateCopyright@3rd wave Media par Copyright@2022 pour pour plus de professionnalisme et de serieux .

**Comment by Ab0698** [comment]
@proxima-admin , @abdounasser202 , @franklinlemaire , il y'a aussi le blog qu'il faut revoir , moi je propose que le blog respecte les mm principes de chartes graphiques que l'integralité du site web , c'est a dire sont entête et sont fond doivent avoir les mm couleurs , aussi il qu'on apporte une touche d'esthetisme sur ce blog . après analyse l'on constate qu'il y'a beaucoup de visiteur dans le blog .Que faire pour attirer du trafic sur le site web et en particulier sur le blog ?

**Comment by abdounasser202** [comment]
@Ab0698 @elmaroufa

**Comment by abdounasser202** [comment]
@franklinlemaire que penses-tu des idées de @Ab0698 proposées plus haut ?

**Comment by franklinlemaire** [comment]
@abdounasser202 @Ab0698 je suis d'accord sur premier point, concernant le second je ne trouve pas d'inconvénients avec ces images qui sont assez explicites sur l'environnement de la start-up donc pas besoin d'une vidéo, je ne comprends pas très bien le point numéro trois et enfin d'accord pour le quatrième point concernant. je vous donne mon avis d'ici quelques temps

**Comment by Ab0698** [comment]
@franklinlemaire le point numero 3 fais allusion a la partie qui sommes nous sur la page d'acceuil , cette parti je propose qu'on la presente sur la page présentation

**Comment by franklinlemaire** [comment]
Bonjour à tous, @Ab0698 sur une page présentation ou sur une section de la page index.html ci? car je me dis que l'idée de base est de tout représenter sur cette page.

**Comment by abdounasser202** [comment]
Pour éclaircir les points mentionnés par Bouhari

Point 1- c'est OK mais les liens Youtube et Blog doivent rester, un header est une porte d'entrée, elle doit être explicite

Point 2- les images sont OK, mais surtout pas de vidéo, ça rendrait la page plus lourde ce qui n'est pas bien pour le référencement. Pour trouver de nouvelles images, faut aller sur iwaria.com, on y trouve des images libres de droits. Aussi penser à rendre les images légères sur tinypng.com

Point 3- OK, mais tout doit tenir sur la seule page index. Ce site est un site statique dont la page principale doit avoir toutes les informations importantes, de telle sorte que les informations sont facilement indexées par les moteurs de recherche. C'est pourquoi nous utilisons le titre qui sommes nous qui à mon sens est mieux évocateur

Point 4- NON, suis pas d'accord. Certes il faut ajouter le contenu pour le privacy mais ça requiert une action de rédaction juridique. Pour le moment on laisse ça comme ça. D'autres parts, faut savoir que les titres doivent être parlant donc mettre contact tout court ne montre pas une proximité avec le visiteur. Les messages ne doivent pas être secs.

La mention de 3rd wave media est obligatoire parce que c'est leur template qu'on utilise donc si on l'enlève on viole les droits d'utilisation

Concernant le blog, faut le laisser tel quel, le modifier est tout un autre projet puisqu'il tourne sur un autre outil ailleurs

Et le lien de AlphaDSF qui ne fonctionne pas doit renvoyer vers la nouvelle page AlphaDSF. Actuellement ce lien ne fonctionne pas parce que le serveur de AlphaDSF a été désactivé, ce serveur permettait de prendre les commandes

En conclusion la page d'accueil doit avoir toutes les informations importantes et seuls les produits doivent avoir leur propre page, présentation, contact doivent être dans la page d'accueil 

@franklinlemaire @Ab0698 @elmaroufa @ousmab @MohamedSouleiman

**Comment by franklinlemaire** [comment]
@abdounasser202 merci beaucoup pour les réponses assez édifiantes . Concernant le point 1 de ce ticket quelles sont les infos à ajouter ou supprimer ?

**Comment by abdounasser202** [comment]
> @abdounasser202 merci beaucoup pour les réponses assez édifiantes . Concernant le point 1 de ce ticket quelles sont les infos à ajouter ou supprimer ?

@franklinlemaire Tu parles du point 1 dans la description du ticket ou bien du point 1 dans les suggestions de Bouhari 

Dans la description du ticket c'est clair : la présentation de proxima et le contenu des balises title et meta description doivent être mis à jour

Concernant le header dans les suggestions de Bouhari il faut les liens Accueil, Présentation, Produits, Youtube, Blog et Contact

Le lien Produits sera un dropdown qui va derouler les liens de nos produits 

Tu peux trouver notre présentation dans cette image de notre récent flyer
![IMG_20221005_121240_483.png](https://user-images.githubusercontent.com/11424142/194037044-fcc3a938-9336-4d73-8185-6262591aca18.png)

**Comment by franklinlemaire** [comment]
@abdounasser202 merci beaucoup pour les précisions

**Comment by franklinlemaire** [comment]
> Le site web proxima.cm est en ligne et déployé sur GitHub Pages
> 
> L'objectif de ce ticket est de mettre à jour le contenu du site web:
> 
> 1. la présentation, le titre et la descption meta pour le référencement SEO doit être mise à jour
> 2. tous les liens qui sont sur la page du site web doivent redirigé vers des pages existantes
> 3. Ajouter les pages pour nos produits AlphaDSF, ProximaSMS, Baker et Schooler



Bonjour à tous, M. @abdounasser202 concernant ce 3e point j'aimerai savoir ce que les pages de ces différents produits vont nous présenter. Merci

**Comment by Ab0698** [comment]
PR Created https://github.com/proxima-cm/proxima-cm.github.io/pull/9

**Comment by elmaroufa** [comment]
@franklinlemaire j'ai vu ton travail, tu a respecté les 3 points citer plus hauts.
Mais il y a un souci au niveau du menu produit, regarde bien :



![Image](https://user-images.githubusercontent.com/25580629/196060133-6c736bad-c2db-42e2-be74-d4f632a3e9f6.png)



![Image](https://user-images.githubusercontent.com/25580629/196060169-f249134b-29b1-42b8-b5a8-40fdc4084635.png)

@franklinlemaire il faut changer la couleur orange, c'est n'est pas bon. Merci

**Comment by elmaroufa** [comment]
@franklinlemaire au niveau du menu "PRODUIT > " il faut retirer le ">", il faut revoir la taille de police des éléments du menu aussi.

**Comment by abdounasser202** [comment]
@franklinlemaire tout est OK

**Comment by franklinlemaire** [comment]
D'accord merci!
