### ISSUE TITLE
Page web AlphaDSF

### ISSUE THREAD

**Issue by proxima-admin** [proxima-cm/proxima-cm.github.io#2]
Ajouter une page pour le produit AlphaDSF --> cf https://github.com/proxima-cm/proxima-cm.github.io/issues/2#issuecomment-1328347469

**Comment by Ab0698** [comment]
Bonjour @proxima-admin , @abdounasser202 j'ai besoin des informations necessaires pour pouvoir creer la page alpha dsf . Merci

**Comment by abdounasser202** [comment]
Désolé @Ab0698 c'est plutôt sur le ticket https://github.com/proxima-cm/proxima-cm.github.io/issues/5 Page web schooler que tu dois travailler, c'est juste une erreur de ma part

**Comment by Ab0698** [comment]
ok

**Comment by abdounasser202** [comment]
Page AlphaDSF à refaire @Ab0698 
RDV pour une session de travail demain

**Comment by abdounasser202** [comment]
@Ab0698 @elmaroufa @MohamedSouleiman j'ai corrigé les erreurs de conflits et la branche 2-AlphaDSF-webpage est au même niveau que la branche master-dev concernant la page d'accueil

@ousmab lis un peu ce que j'ai écrit là si je n'ai rien oublié

@Ab0698 voici pas à pas ce que tu dois faire :

Avant de commencer à travailler, fais ceci

`
git checkout 2-AlphaDSF-webpage
git pull origin 2-AlphaDSF-webpage
`

Ne fais aucun merge.

Ensuite :

- [ ] Pour le référencement SEO une balise title qui va contenir AlphaDSF: logiciel de génération de la DSF système OHADA
- [ ] Puis une balise meta description qui sera : Utilisez AlphaDSF pour générer vos états financiers et les envoyer à la DGI en un seul clic
- [ ] La page de AlphaDSF doit avoir la même charte graphique que celle de la page d'accueil, c'est-à-dire même couleurs, même police d'écriture, même menus et même footer (pied de page)

Au niveau du contenu de la page de AlphaDSF if faut
- [ ] il faut un titre en balise h1 qui sera : AlphaDSF permet aux comptables de générer la DSF en un clic
- [ ] un sous-titre en balise h2 ou h3 qui sera : Doté d’une ergonomie assez conviviale, AlphaDsf masque toute la complexité liée au traitement en automatisant la procédure d’édition des états, Vous n’avez qu’à importer les balances des deux exercices Comptables N et N-1 et le logiciel s’occupe du reste.
- [ ] Ensuite un bouton dont le titre sera : Obtenir AlphaDSF maintenant. Ce bouton va renvoyer vers la section pour passer les commandes
- [ ] Une section Comment ça marche qui va expliquer comment AlphaDSF fonctionne et qui va afficher cette vidéo youtube: https://youtu.be/i-UlMy8cATg?t=109 . Ne modifie pas ce lien, note bien qu'il a t=109 à la fin
- [ ] Une section Ils nous font confiance qui va contenir les logos des entreprises qui ont déjà utilisé AlphaDSF: Bocom, Stradel, etc...
- [ ] Une section témoignage dans laquelle on va recueillir les témoignages de ceux qui ont déjà utiliser AlphaDSF
- [ ] Enfin une section passer la commande qui affiche la liste des prix comme celle qui existe actuellement sur la page. Chaque section aura un bouton qui va permettre de passer sa commande via whatsapp sur un numéro qu'on va définir
- [ ] Une dernière chose, le fichier alphadsf.html doit se situer dans le dossier alphadsf et il doit s'appeler index.html et non alphdsf.html

**Comment by abdounasser202** [comment]
L'ancienne page de AlphaDSF est ici: https://github.com/proxima-cm/alphadsf_landing/blob/master/home/index.html @Ab0698

**Comment by abdounasser202** [comment]
Terminé
