### ISSUE TITLE
Page web Schooler

### ISSUE THREAD

**Issue by proxima-admin** [proxima-cm/proxima-cm.github.io#5]
Ajouter une page web pour le produit Schooler

**Comment by Ab0698** [comment]
ok

**Comment by Ab0698** [comment]
@abdounasser202  jattend les informations et les differents éléments pour pouvoir commencer . Merci

**Comment by abdounasser202** [comment]
@Ab0698 voici les éléments

Il s'agit d'un page simple qui doit avoir les éléments suivants

1/ Expliquer la valeur que le logiciel apporte (titre)

2/ Expliquer comment on cré cette valeur (sous-titre)

3/ Laisser l'utilisateur la visualiser (visuel des fonctionnalités importantes)

4/ Rendre crédible (clients qui utilisent le logiciel).

5/ Permettre le passage à l'étape suivante (contact)

Le fichier qui présente le logiciel est sur Drive: https://docs.google.com/document/d/18Rwz7hxdzDxlhB0E7CDVElOqsnLb4CdbLTiZG8_-kfM/edit?usp=sharing

Il faut te rapprocher de @elmaroufa si tu as besoin des visuels, comme ça il va démarrer l'application et prendre les captures d'écran

NB: cette page doit épouser la charte graphique du site, c'est à dire les couleurs et la police

@MohamedSouleiman @ousmab

**Comment by Ab0698** [comment]
ok

**Comment by elmaroufa** [comment]
J'ai placé ce code en review, @franklinlemaire il faut faire la vérification de son code et vérifier la page web de schooler sur ta machine.

**Comment by franklinlemaire** [comment]
@elmaroufa bien noté

**Comment by franklinlemaire** [comment]
@Ab0698 l'idéal était de nommer ta branche comme la norme avait été indiqué c'est à dire par rapport au nom du ticket...

**Comment by Ab0698** [comment]
ok

**Comment by Ab0698** [comment]
PR finished https://github.com/proxima-cm/proxima-cm.github.io/pull/8

**Comment by abdounasser202** [comment]
@Ab0698 @elmaroufa voici un document récapitulatif sur Schooler
https://docs.google.com/document/d/150b9v7yovubwaF_NGU-UFxQDieOOrehp/edit?usp=sharing&ouid=102136810853695913790&rtpof=true&sd=true

**Comment by abdounasser202** [comment]
Page Schooler à refaire @Ab0698 
RDV pour une session de travail demain

**Comment by abdounasser202** [comment]
updated and merged into master-dev branch
